source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYNetworking_Example', :exclusive => true do
  pod 'HYNetworking', :path => '../'
end

target 'HYNetworking_Tests', :exclusive => true do
  pod 'HYNetworking', :path => '../'

  
end
